# followed_authors.yaml
followed_authors:
  - name: Erika Janitz
    orcid: "0000-0003-3299-9165"
    names:
      - Erika Janitz
      - E. Janitz
  - name: Mark Fox
    orcid: "0000-0002-9025-2441"
    names:
      - A. M. Fox
      - A. Mark Fox

