# ./config/keywords.yaml
keywords:
  - nitrogen vacancy
  - nitrogen-vacancy
  - silicon vacancy
  - silicon-vacancy
  - diamond defect
  - NV center
  - NV centre
  - color center
  - colour centre
  - quantum spin defect
  - quantum sensing
  - quantum point defect
  - T center
  - T centre
  - ODMR
  - optically detected magnetic resonance
